[package]
name = "example"
version = "0.1.0"
edition = "2021"
resolver = "2"

[dependencies]
dynamo-subscriber = { path = ".." }
aws-config = { version = "1.0.1" }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
tokio-stream = "0.1.14"
