[package]
name = "dynamo-subscriber"
version = "0.0.1"
edition = "2021"

[dependencies]
async-recursion = "1.0.5"
async-trait = "0.1.74"
aws-config = { version = "1.0.0", features = ["behavior-version-latest"] }
aws-sdk-dynamodb = "0.39.0"
aws-sdk-dynamodbstreams = "0.39.0"
thiserror = "1.0.50"
tokio = { version = "1", features = ["rt", "sync", "time"] }
tracing = "0.1"
