[package]
name = "dynamo-subscriber"
version = "0.0.1"
edition = "2021"
resolver = "2"

[dependencies]
async-recursion = "1.0.5"
async-trait = "0.1.74"
aws-config = { version = "1.0.0", features = ["behavior-version-latest"] }
aws-sdk-dynamodb = "0.39.0"
aws-sdk-dynamodbstreams = "0.39.0"
thiserror = "1.0.50"
tokio = { version = "1", features = ["rt", "sync", "time"] }
tokio-stream = "0.1.14"
tokio-util = "0.7.10"
tracing = "0.1"

[dev-dependencies]
itertools = "0.12"
tokio = { version = "1", features = ["macros"] }
