on:
  pull_request:
  push:
    branches: [ 'main' ]
    tags-ignore: [ '*' ]
  workflow_dispatch:

name: Test

env:
  RUST_BACKTRACE: full
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable

      - name: Run cargo check
        run: cargo check --all-features

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable

      - name: Use cache
        uses: Swatinem/rust-cache@v2

      - name: Run cargo test
        shell: bash
        run: ./test.sh

  lints:
    name: Lints
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: clippy

      - name: Run cargo clippy
        run: cargo clippy --all --tests --all-features -- -D warnings
